//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PgSqlContainer : DbContext
    {
        public PgSqlContainer()
            : base("name=PgSqlContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_antennaconfig> t_antennaconfig { get; set; }
        public virtual DbSet<t_antennahealth> t_antennahealth { get; set; }
        public virtual DbSet<t_asubtask> t_asubtask { get; set; }
        public virtual DbSet<t_ataskinfo> t_ataskinfo { get; set; }
        public virtual DbSet<t_datamanagerlog> t_datamanagerlog { get; set; }
        public virtual DbSet<t_department> t_department { get; set; }
        public virtual DbSet<t_devres> t_devres { get; set; }
        public virtual DbSet<t_devresstatuslog> t_devresstatuslog { get; set; }
        public virtual DbSet<t_devrestype> t_devrestype { get; set; }
        public virtual DbSet<t_devrestypeinfo> t_devrestypeinfo { get; set; }
        public virtual DbSet<t_fsubtask> t_fsubtask { get; set; }
        public virtual DbSet<t_ftaskinfo> t_ftaskinfo { get; set; }
        public virtual DbSet<t_mswitchconfig> t_mswitchconfig { get; set; }
        public virtual DbSet<t_rescountdata> t_rescountdata { get; set; }
        public virtual DbSet<t_role> t_role { get; set; }
        public virtual DbSet<t_sat> t_sat { get; set; }
        public virtual DbSet<t_station> t_station { get; set; }
        public virtual DbSet<t_stationtask> t_stationtask { get; set; }
        public virtual DbSet<t_substationtask> t_substationtask { get; set; }
        public virtual DbSet<t_subtask> t_subtask { get; set; }
        public virtual DbSet<t_subtasktype> t_subtasktype { get; set; }
        public virtual DbSet<t_sysconfig> t_sysconfig { get; set; }
        public virtual DbSet<t_taskdev> t_taskdev { get; set; }
        public virtual DbSet<t_taskinfo> t_taskinfo { get; set; }
        public virtual DbSet<t_tasktemplate> t_tasktemplate { get; set; }
        public virtual DbSet<t_tasktemplatedev> t_tasktemplatedev { get; set; }
        public virtual DbSet<t_tasktype> t_tasktype { get; set; }
        public virtual DbSet<t_thunderdata> t_thunderdata { get; set; }
        public virtual DbSet<t_user> t_user { get; set; }
        public virtual DbSet<t_userlog> t_userlog { get; set; }
        public virtual DbSet<t_weatherdata> t_weatherdata { get; set; }
    }
}
