//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_antennahealth
    {
        public string id { get; set; }
        public Nullable<int> sortid { get; set; }
        public Nullable<System.DateTime> msgtime { get; set; }
        public Nullable<System.DateTime> systime { get; set; }
        public Nullable<int> datatype { get; set; }
        public Nullable<int> health { get; set; }
        public Nullable<float> fw { get; set; }
        public Nullable<float> fy { get; set; }
        public Nullable<float> xhqd { get; set; }
        public Nullable<int> @lock { get; set; }
        public Nullable<float> djjcx { get; set; }
        public Nullable<float> djjcy { get; set; }
        public Nullable<float> kt1wd { get; set; }
        public Nullable<float> kt1sd { get; set; }
        public Nullable<float> wsd1wd { get; set; }
        public Nullable<float> wsd1sd { get; set; }
        public Nullable<float> sj1 { get; set; }
        public Nullable<float> fwdj1 { get; set; }
        public Nullable<float> fwdj2 { get; set; }
        public Nullable<float> fydj1 { get; set; }
        public Nullable<float> fydj2 { get; set; }
        public Nullable<float> sxdljxdy1 { get; set; }
        public Nullable<float> sxdljxdy2 { get; set; }
        public Nullable<float> sxdljxdy3 { get; set; }
        public Nullable<float> sxdljxiandy1 { get; set; }
        public Nullable<float> sxdljxiandy2 { get; set; }
        public Nullable<float> sxdljxiandy3 { get; set; }
        public Nullable<float> sxdljxdl1 { get; set; }
        public Nullable<float> sxdljxdl2 { get; set; }
        public Nullable<float> sxdljxdl3 { get; set; }
        public Nullable<float> txzmx { get; set; }
        public Nullable<float> txzmy { get; set; }
        public Nullable<float> txzmz { get; set; }
        public Nullable<int> log { get; set; }
    }
}
