//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_antennaconfig
    {
        public string id { get; set; }
        public string antennaname { get; set; }
        public string resid { get; set; }
        public string resname { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> height { get; set; }
        public string stationid { get; set; }
        public string station { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public string editper { get; set; }
        public Nullable<short> antenidex { get; set; }
    }
}
