//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ataskinfo
    {
        public string id { get; set; }
        public string taskname { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createperid { get; set; }
        public string createper { get; set; }
        public string tasktype { get; set; }
        public Nullable<short> tasktypeid { get; set; }
        public Nullable<System.DateTime> begintime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<int> taskinterval { get; set; }
        public Nullable<short> taskrtstatusid { get; set; }
        public string taskcomment { get; set; }
        public string datapath { get; set; }
        public string station { get; set; }
        public string stationid { get; set; }
        public string antenname { get; set; }
        public Nullable<short> antenid { get; set; }
        public string reserved1 { get; set; }
        public string reserved2 { get; set; }
        public string tasklog { get; set; }
        public string approvalstatus { get; set; }
        public string approvalremark { get; set; }
        public Nullable<short> approvalstatusid { get; set; }
        public string taskrtstatus { get; set; }
    }
}
