//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_devresstatuslog
    {
        public string id { get; set; }
        public string resid { get; set; }
        public string resname { get; set; }
        public string rescode { get; set; }
        public Nullable<int> restypeid { get; set; }
        public string restype { get; set; }
        public Nullable<int> restypeinfoid { get; set; }
        public string restypeinfo { get; set; }
        public string resstatus { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> statustime { get; set; }
        public string ip { get; set; }
        public Nullable<int> port { get; set; }
        public string station { get; set; }
        public string stationid { get; set; }
    }
}
