//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ftaskinfo
    {
        public string id { get; set; }
        public string taskname { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createperid { get; set; }
        public string createper { get; set; }
        public string tasktype { get; set; }
        public Nullable<short> tasktypeid { get; set; }
        public Nullable<System.DateTime> begintime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<int> taskinterval { get; set; }
        public Nullable<short> taskstatus { get; set; }
        public string taskcomment { get; set; }
        public string datapath { get; set; }
        public string station { get; set; }
        public string stationid { get; set; }
        public string antenname { get; set; }
        public string antenid { get; set; }
        public Nullable<short> returnstatus { get; set; }
        public string reserved1 { get; set; }
        public string reserved2 { get; set; }
        public string tasklog { get; set; }
        public Nullable<short> antenidex { get; set; }
        public Nullable<short> cz_receive_band { get; set; }
        public Nullable<short> cz_filter_band { get; set; }
        public Nullable<short> cz_work_mode { get; set; }
        public Nullable<short> cz_work_frequency { get; set; }
        public Nullable<int> cz_captimelen { get; set; }
        public Nullable<short> cz_samplerate { get; set; }
        public Nullable<short> cz_intervaltime { get; set; }
        public Nullable<double> cz_if { get; set; }
        public Nullable<short> cz_dynamic_adjust { get; set; }
        public Nullable<short> cz_satlist { get; set; }
        public Nullable<short> cz_modeselect { get; set; }
    }
}
