//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_station
    {
        public string id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> regtime { get; set; }
        public Nullable<bool> isdel { get; set; }
        public Nullable<short> stationtype { get; set; }
        public string ftppath { get; set; }
        public string ftpuser { get; set; }
        public string ftppasswd { get; set; }
    }
}
