//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_subtask
    {
        public string id { get; set; }
        public string taskid { get; set; }
        public Nullable<short> satid { get; set; }
        public string satname { get; set; }
        public Nullable<System.DateTime> begintime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<float> endazimuth { get; set; }
        public Nullable<float> beginelevation { get; set; }
        public Nullable<float> beginazimuth { get; set; }
        public Nullable<float> endfelevation { get; set; }
        public Nullable<short> pointinterval { get; set; }
    }
}
