//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sysconfig
    {
        public string id { get; set; }
        public string rmq_serverip { get; set; }
        public string rmq_serveruser { get; set; }
        public string rmq_serverpsd { get; set; }
        public Nullable<int> fb_localudpport { get; set; }
        public string fb_totalctlip { get; set; }
        public Nullable<int> fb_totalctlport { get; set; }
        public string fb_inthewayip { get; set; }
        public Nullable<int> fb_inthewayport { get; set; }
        public string ftp_dataserverip { get; set; }
        public Nullable<int> ftp_dataserverport { get; set; }
        public string ftp_dataserveruser { get; set; }
        public string ftp_dataserverpsd { get; set; }
        public Nullable<int> res_monitorinterval { get; set; }
        public Nullable<int> res_outlineinterval { get; set; }
        public Nullable<short> fb_bd3beginindex { get; set; }
        public Nullable<short> fb_bd3endindex { get; set; }
        public Nullable<short> ant_healthgate { get; set; }
        public Nullable<short> tsk_planinterval { get; set; }
        public Nullable<int> thd_autostopwarinterval { get; set; }
        public Nullable<int> thd_notneedwarinterval { get; set; }
        public Nullable<short> dm_antendatadays { get; set; }
        public Nullable<short> dm_thddatadays { get; set; }
        public Nullable<short> dm_whrdatadays { get; set; }
        public Nullable<short> dm_dmlogdatadays { get; set; }
        public Nullable<short> dm_dohour { get; set; }
        public string oh_editer { get; set; }
        public Nullable<System.DateTime> oh_edittime { get; set; }
        public string oh_reserve1 { get; set; }
        public string oh_reserve2 { get; set; }
        public string oh_reserve3 { get; set; }
    }
}
