//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_taskdev
    {
        public string id { get; set; }
        public string taskid { get; set; }
        public string resid { get; set; }
        public string resname { get; set; }
        public string param { get; set; }
        public Nullable<short> index { get; set; }
        public Nullable<int> restypeid { get; set; }
        public Nullable<int> restypeinfoid { get; set; }
    }
}
