//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_thunderdata
    {
        public string id { get; set; }
        public Nullable<int> sortid { get; set; }
        public Nullable<int> typemsg { get; set; }
        public Nullable<int> datalen { get; set; }
        public Nullable<System.DateTime> timemsg { get; set; }
        public Nullable<int> eqptype { get; set; }
        public Nullable<int> iostat { get; set; }
        public Nullable<int> thundercnt { get; set; }
        public Nullable<int> warlevel { get; set; }
        public Nullable<float> elecpower { get; set; }
        public Nullable<float> elecpoweraver { get; set; }
        public Nullable<float> elecpowerrate { get; set; }
        public Nullable<float> power { get; set; }
        public Nullable<float> eqptemp { get; set; }
        public Nullable<int> funspeed { get; set; }
        public string devresid { get; set; }
    }
}
