//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_userlog
    {
        public string id { get; set; }
        public string username { get; set; }
        public string logincode { get; set; }
        public string opertype { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> usertime { get; set; }
        public string ip { get; set; }
        public string department { get; set; }
    }
}
