//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSqlDemo.Pgsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_weatherdata
    {
        public string weatherid { get; set; }
        public string weathertype { get; set; }
        public string weathercontent { get; set; }
        public Nullable<System.DateTime> weathertime { get; set; }
    }
}
